#! /bin/bash
# ifs.sh

IFS=":"
while read -e prenom nom role
do
IFS=":"
echo -e "Prenom:$prenom nom:$nom role:$role"

prenom2l=$(echo ${prenom:0:2});
nom1l=$(echo ${nom:0:1});
trigramme=$prenom2l$nom1l
echo $trigramme
done < /home/skilz/Documents/Linux/UsersLinux
