#! /bin/bash
# ifs.sh
#Création groupes
for grp in BrancheDeveloppement BrancheRecherche BrancheIngenieurie techtech Admin
do
groupadd $grp
done
#Séparateur de texte initialisation
IFS=":";
while read -e prenom nom role branche dossier dossier2 admin
do
#Stock la lecture dans des variables
prenom=$prenom; role=$role; branche=$branche; dossier=$dossier; dossier2=$dossier2; admin=$admin

#Création trigramme
IFS=":"
prenom2l=$(echo ${prenom:0:2});
nom1l=$(echo ${nom:0:1});
trigramme=$prenom2l$nom1l

#Création password
password=$(openssl rand -base64 7);
#Création fichier passwords
touch passwords /home/

President="President"; Chercheur="Chercheur"; Developpeur="Developpeur"; Ingenieur="Ingenieur"; Chef="Chef de service";

#Conditions création users + répertoires et assignation groupes
set -x
	trigramme=$prenom2l$nom1l;
        #Conditions création users + répertoires et assignation groupes
        if [ "$role" == "$President" ]
        then useradd -m --home-dir /home/$trigramme -G Admin,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $password) $trigramme
        mkdir -v -p /home/$trigramme/$dossier
	      chmod 1700 /home/$trigramme
	      chown -R $trigramme:$trigramme /home/$trigramme
        fi

        if [ "$branche" == "$branche" ]
        then mkdir -v -p /home/$branche/$dossier
	      chmod 1760 /home/$branche
	      chown -R $trigramme:BigBoss /home/$branche
        fi

        if [ "$role" == "$Chercheur" ]
        then useradd -m --home-dir /home/$trigramme -G BrancheRecherche,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $password) $trigramme
        mkdir -v -p /home/$trigramme/$dossier
	      ln -s /home/BrancheRecherche /home/$trigramme/BrancheRecherche
	      chmod 1764 /home/$trigramme
	      chown -R $trigramme:$trigramme /home/$trigramme
        fi

        if [ "$role" == "$Developpeur" ]
        then useradd -m --home-dir /home/$trigramme -G BrancheDeveloppement,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $password) $trigramme
        mkdir -v -p /home/$trigramme/$dossier
	      ln -s /home/BrancheDeveloppement /home/$trigramme/BrancheDeveloppement
      	chmod 1764 /home/$trigramme
	      chown -R $trigramme:$trigramme /home/$trigramme
        fi

        if [ "$role" == "$Ingenieur" ]
        then useradd -m --home-dir /home/$trigramme -G BrancheIngenieurie,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $password) $trigramme
      	mkdir -v -p /home/$trigramme/$dossier
    	  ln -s /home/BrancheIngenieurie /home/$trigramme/BrancheIngenieurie
    	  chmod 1764 /home/$trigramme
	      chown -R $trigramme:$trigramme /home/$trigramme
        fi

        if [ "$role" == "$Chef" ]
        then useradd -m --home-dir /home/$trigramme -G Admin,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $password) $trigramme
        mkdir -v -p /home/$trigramme/$dossier2
        mkdir -v -p /home/$trigramme/$admin
	      ln -s /home/$branche /home/$trigramme/$branche
      	chmod 1760 /home/$trigramme/$admin
      	chmod 1764 /home/$trigramme/$dossier2
      	chown -R $trigramme:$trigramme /home/$trigramme
	      chown -R $trigramme:$trigramme /home/$trigramme
        fi
	trigramme=$prenom2l$nom1l;

for i in 1
        do
                echo $trigramme $password >> /home/passwords
done
set +x
done < /home/users
