#! /bin/bash
# ifs.sh

IFS=":";
while read -e prenom nom role branche dossier dossier2 admin
do
IFS=":"
prenom2l=$(echo ${prenom:0:2});
nom1l=$(echo ${nom:0:1});
trigramme=$prenom2l$nom1l
 
if [[ $role == "President" ]];then
useradd $trigramme --create-home --groups BigBoss,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $trigramme) $trigramme
mkdir -v -p /home/$trigramme/$dossier
	
elif [[ $role == "Chercheur" ]];then 
useradd $trigramme --create-home --groups BrancheRecherche,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $trigramme) $trigramme
mkdir -v -p /home/$trigramme/$dossier
	
elif [[ $role == "Developpeur" ]];then
useradd $trigramme --create-home --groups BrancheDeveloppement,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $trigramme) $trigramme
mkdir -v -p /home/$trigramme/$dossier

elif [[ $role == "Ingenieur" ]];then
useradd $trigramme --create-home --groups BrancheIngenieur,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $trigramme) $trigramme
mkdir -v -p /home/$trigramme/$dossier

elif [[ $role == "Chef de service" ]];then
useradd $trigramme --create-home --groups Admin,techtech -p $(perl -e 'print crypt($ARGV[0], "password")' $trigramme) $trigramme
mkdir -v -p /home/$trigramme/$dossier/$dossier2

elif [[ $branche == $branche ]];then
mkdir -v -p /home/$branche/$dossier
else 
	echo "error"
fi

done < /home/skilz/Documents/Linux/users2
